project:
  type: website
  output-dir: docs

website:
  title: "MAT 118: Elementary Statistics"
  logo: images/dcc-logo.png
  logo-alt: "Dutchess Community College Logo"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: file-pdf
        href: Syllabus_Math_118-20-SP2026.pdf
        text: "Download PDF"